#定义当前版本
version: "3"
#定义我们的服务对象
services:
#自定义的服务名称
  nginx:
    #镜像名称，默认拉取本地镜像，没有的话从远程获取
    image: registry.cn-hangzhou.aliyuncs.com/jasper_kd/nginx:v1.0
    #自定义容器的名称
    container_name: nginx-server
    #将宿主机的5000端口映射到容器的80端口
    ports:
      - "80:80"
      - "443:443"
      # 将会映射8080到8085这个范围内的端口
      - 8080-8085:8080-8085
    #将宿主机的./www目录和容器的/var/www/html目录进行绑定，并设置rw权限
    volumes:
      - /Users/a37/code:/code:rw
      - ./nginx/nginx:/etc/nginx:rw
      - ./nginx/cert:/data/cert:rw
      - /Users/a37/www/logs/nginx:/www/logs/nginx:rw
      #容器只能从主机的/ etc / localtime读取
      - /etc/localtime:/etc/localtime:ro
    #容器是否随docker服务启动重启
    restart: always
    #容器加入名为default的网络
    networks:
      - default

  php:
    image: registry.cn-hangzhou.aliyuncs.com/jasper_kd/php7.4:v1.0
    container_name: php-container
    volumes:
      - ./php/etc:/usr/local/etc:rw
      - /Users/a37/code:/code:rw
      - /Users/a37/www/logs/php:/www/logs/php:rw
      #容器只能从主机的/ etc / localtime读取
      - /etc/localtime:/etc/localtime:ro
    restart: always
    cap_add:
      - SYS_PTRACE
    ports:
      - "3366:3306" # 映射数据库端口
      - "9000:9000"
    networks:
      - default

  redis:
    #hostname: redis_dk
    image: registry.cn-hangzhou.aliyuncs.com/jasper_kd/redis4:v1.0
    container_name: redis-server
    restart: always
    command: redis-server /etc/redis.conf # 启动redis命令
    volumes:
      - ./redis/data:/data:rw
      - ./redis/redis.conf:/etc/redis.conf:rw
      #容器只能从主机的/ etc / localtime读取
      - /etc/localtime:/etc/localtime:ro
    #ports:
      #- "6399:6379"
    network_mode: service:php
    depends_on:
      - php
  # 数据库，如果不使用的话就关掉
#  mysql:
#    image: registry.cn-hangzhou.aliyuncs.com/jasper_kd/mysql5.7:v.10
#    container_name: mysql-server
#    #    ports:
#    #      - "3366:3306"
#    volumes:
#      - ./mysql/data:/var/lib/mysql/:rw
#      - ./mysql/conf.d:/etc/mysql/conf.d
#      #容器只能从主机的/ etc / localtime读取
#      - /etc/localtime:/etc/localtime:ro
#    restart: always
#    #    networks:
#    #      - default
#    environment:
#      # 默认root密码，记得改掉
#      MYSQL_ROOT_PASSWORD: "c018edf028e98547173fd3af31d30733"
#    network_mode: service:php
#    depends_on:
#      - php
networks:
  #创建了一个自定义的网络叫做default
  default:
